### ISSUE TITLE
Not able to import TerminalEmulator from website/services/wasm/tunshell_client

### ISSUE THREAD

**Issue by vijayababu45** [TimeToogo/tunshell#46]
I need to integrate the website part into my site, i am not able to import TerminalEmulator from website/services/wasm/tunshell_client since the wasm folder is not found inside the services folder. I have tried with cargo build, was not able to get the wasm folder inside services folder. Can you pls help me on this, to get this website up and running inside my website.

**Comment by TimeToogo** [comment]
HI @vijayababu45,

Can you please share more details on the integration you are performing? 
Are you planning to host your own relay servers?

Thanks

**Comment by vijayababu45** [comment]
Hi,
I will integrating only the website part and will connecting to target host via tunshell relay server. its like requesting from our portal to tunshell relay serve and connecting to target host. 

Many Thanks

**Comment by TimeToogo** [comment]
The default relay servers are hosted by me on a personal AWS account.
It used to have AWS credits but those have since run out and I am now paying for the hosting myself.
Hence I will not permit a third-party service using those services without having a full understanding of how they will be used. So please elaborate on what the function of your "website", is and how tunshell will be used. 
There is always the option for you to self-host the relay services as described in the documentation.

**Comment by TimeToogo** [comment]
Closing due to lack of response. Feel free to reopen if further clarification needed.
