### ISSUE TITLE
custom setup

### ISSUE THREAD

**Issue by GopherJ** [TimeToogo/tunshell#6]
Hi, I'm very interested in this solution, thanks for making it. The problem that I would like to solve using tunshell is managing potential thousands of IOT devices in private network (behind firewall).

I would like to know:

1. Is it easy to setup my custom relay server for generating peer keys? Do you plan to make details guide on it?
2. How can I execute custom command instead of having an interactive shell?
3. What's the current arch list supported? (basically I would like to use on x86_64 and mips )

Thanks in advance

**Comment by TimeToogo** [comment]
Hi @GopherJ,

Thanks for your interest, based on your use case description I'm not sure if Tunshell is the right fit for you. The current design is more to support single shell sessions rather than constantly listening for new connections as you may be after. But to answer your questions:

1. Yes this is possible and I've now added a guide on this [here](https://github.com/TimeToogo/tunshell/tree/master/aws/)
2. This is not currently supported by the clients. Currently the client will wait for a connection, initiate a remote shell session and exit once that session finishes.
3. I've added a list of supported architectures [here](https://github.com/TimeToogo/tunshell#supported-targets-for-client). MIPS is not currently supported but I would welcome PR's for targeting different architectures if they don't add a large maintenance overhead.

Thanks
